### ISSUE TITLE
Build error in VS2015

### ISSUE THREAD

**Issue by cristianst85** [dlech/KeePassPluginDevTools#2]
Now, moving to the next issue. I'm getting these errors in SamplePlugin project when building the solution:

```
Error       This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\PlgxTool.0.1.4\build\PlgxTool.targets.    SamplePlugin    D:\Repositories\KeePassPluginDevTools\SamplePlugin\SamplePlugin.csproj  128 
Severity    Code    Description Project File    Line    Suppression State

Error       NuGet Package restore failed for project SamplePlugin: System.InvalidOperationException: Unable to find version '0.1.4' of package 'PlgxTool'.
   at NuGet.PackageManagement.PackageDownloader.<GetDownloadResourceResultAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<RestorePackageAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.PackageRestoreManager.<RestorePackageAsync>d__39.MoveNext().          0   
```

**Comment by dlech** [comment]
`0.1.4` was never published on nuget. Change the package version to `1.0.0`.

**Comment by cristianst85** [comment]
I've created a PR. Manually editing packages.config did the trick.
